# server information
[server]
brokerId = "broker"
port = 5559
granularity = 5
messageProcessors = 2
planCreatorAddress = 54.82.181.246:7001
loadBalancerAddress = 54.243.10.234:5559
# logConfFile = "./test-log.xml" # specify another config file to be used

    # server mode specific information (only one should be uncommented)
    [server.mode]
    name = "single"

#   [server.mode]
#    name = "disgb_subscriberMatching"
#    brokerAreaFilePath = "brokerAreas_template.json"
#    brokerCommunicators = 1

#   [server.mode]
#    name = "disgb_publisherMatching"
#    brokerAreaFilePath = "brokerAreas_template.json"
#    brokerCommunicators = 1

#    [server.mode]
#    name = "other"
#    otherMode = "single_noGeo"

