---
- name: Terminate LoadBalancer and Client EC2 instances
  hosts: localhost
  connection: local
  gather_facts: true  
  pre_tasks:
    - include_vars: variables.yml
  tasks:
    - include_tasks: tasks/terminate_clients.yml
    - include_tasks: tasks/terminate_geobrokers.yml
    - include_tasks: tasks/terminate_lb.yml
