---
- name: "Create EC2 instances for Clients"
  ec2:
    key_name: "{{ keypair }}"
    group_id: "{{ client_security_group_id }}"
    instance_type: t3.large
    image: "{{ ami }}"
    wait: true
    count: "{{ directory_count }}"
    vpc_subnet_id: "{{ client_subnet_id }}"
    assign_public_ip: yes
    instance_tags:
        instance_class: clients
    wait_timeout: 1200
  register: ec2
 
- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: clients
  loop: "{{ ec2.instances }}" 
  
- name: Wait for SSH to become open on the host
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    delay: 1
  loop: "{{ ec2.instances }}" 