      
- name: create VPC
  ec2_vpc_net:
    name: " {{ client_id }}-vpc "
    cidr_block: "{{ vpc_cidr_block }}"
  register: created_vpc

    
- name: Create subnet 
  ec2_vpc_subnet:
    vpc_id: "{{ created_vpc.vpc.id }}"
    cidr: "{{ vpc_cidr_block }}"
    tags:
      Name: "{{ client_id }}-subnet"
  register: created_subnet
  
- name: Add subnet_id to variables.yml
  lineinfile:
    path: variables.yml
    regexp: '^client_subnet_id: '
    line: "client_subnet_id: {{ created_subnet.subnet.id }}"
    mode: '0644'

  
- name: Create Internet Gateway
  ec2_vpc_igw:
    vpc_id: "{{ created_vpc.vpc.id }}"
    state: present
    tags:
        Name: "{{ client_id }}-igw"
  register: igw
  
  
- name: Set up public subnet route table
  ec2_vpc_route_table:
    vpc_id: "{{ created_vpc.vpc.id }}"
    tags:
      Name: "{{ client_id }}-rtb"
    subnets:
      - "{{ created_subnet.subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"

  register: public_route_table
    
- name: Create security group
  ec2_group:
    name: "{{ client_id }}-security-group"
    description: "Security group for {{ client_id }} instances"
    vpc_id: "{{ created_vpc.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 0    
        to_port: 65535     
        cidr_ip: 0.0.0.0/0
   
      - proto: icmp
        from_port: -1
        to_port: -1
        cidr_ip: 0.0.0.0/0
  register: created_sec_group

    
- name: "set fact: security group ID"
  set_fact:
    group_id: "{{ created_sec_group.group_id }}"   
   
- name: Add security_group_id to variables.yml
  lineinfile:
    path: variables.yml
    regexp: '^client_security_group_id: '
    line: "client_security_group_id: {{ created_sec_group.group_id }}"
    mode: '0644'   