#- environment: Set AWS default region
#  shell: export AWS_DEFAULT_REGION="{{AWS_DEFAULT_REGION}}"

#- name: Set AWS credentials
#  shell: export AWS_ACCESS_KEY_ID="{{AWS_ACCESS_KEY_ID}}"
    
#- name: Set AWS credentials
#  shell: export AWS_SECRET_ACCESS_KEY="{{AWS_SECRET_ACCESS_KEY}}"

- name: populate /etc/environment with AWS credentials
  become: yes
  lineinfile:
    dest: "/etc/environment"
    state: present
    regexp: "^{{ item.key }}="
    line: "{{ item.key }}={{ item.value}}"
  with_items: "{{ os_environment }}"